---
- name: local install
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo

  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - "{{ inventory_dir }}/vault/secrets.yml"
      when: item|exists
      tags:
        - account
        - user
        - sudo
        - sudoer
        - skel
        - sshkeys
        - samba
        - atom
        - oh-my-zsh
        - zsh

    #
    # - name: debug
    #   debug: var=hostvars[inventory_hostname]
    #   tags:
    #     - account
    #     - user
    #     - sudo
    #     - sudoer
    #     - skel
    #     - sshkeys
    #     - samba
    #
    # - name: install packages
    #   apt: name={{ item }} state=present
    #   with_items:
    #     - vim
    #     - git
    #     - bash-completion
    #     - build-essential

  roles:
    - locales
    - account
    - docker
    - samba
    - dnsmasq
    - packer
    - terraform
    - vagrant
    - aws
    - oh-my-zsh
    - atom
